### ISSUE TITLE
Exploring the possibility of a collaboration

### ISSUE THREAD

**Issue by notakoder** [dhyanKaro/malayalam-transliterator#1]
I'd like to privately discuss the possibility of hosting this transliterator in another language project, and also explore the idea of creating more transliterators. Is there an email address through which I can contact the developer?

**Comment by dhyanKaro** [comment]
> I'd like to privately discuss the possibility of hosting this transliterator in another language project, and also explore the idea of creating more transliterators. Is there an email address through which I can contact the developer?

dhyankaroabhi@gmail.com

Yeah feel free to use it

**Comment by notakoder** [comment]
Noted. You may delete the issue/comment if you are concerned about your email being in public.
